### ISSUE TITLE
Fails with "OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown"

### ISSUE THREAD

**Issue by ThisIsMissEm** [spicyparrot/kafka-kraft-action#14] opened 2024-05-30 11:06 UTC
**Describe the bug**

Fails to find bash (I guess needed by the start/*.sh scripts?)

**To Reproduce**

Try using the action as documented; we also have the following in our workflow, but that shouldn't be the source of the issue:

```
  runs-on: ubuntu-latest

  services:
      postgres:
        # Docker Hub image
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
``` 

**Expected behavior**

Kafka starts, instead we get this log from the action:

```
Run spicyparrot/kafka-kraft-action@v1.1.1
  with:
    kafka-version: 3.7.0
    kafka-topics: webhook-events,1,webhook-failures,1
  env:
    ...
Run actions/checkout@v4
/usr/bin/docker exec  9e37c66c9c6ec5c97bdf1b8d36356506f35c5f824434bf80552f86d3f5570a1f sh -c "cat /etc/*release | grep ^ID"
Syncing repository: spicyparrot/kafka-kraft-action
Getting Git version info
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Determining the default branch
Retrieving the default branch name
Default branch 'trunk'
Downloading the archive
Writing archive to disk
Extracting the archive
/bin/tar xz -C /__w/ccs/ccs/kafka/1d4297d7-525a-45f3-8487-3210550df34e -f /__w/ccs/ccs/kafka/1d4297d7-525a-45f3-8487-3210550df34e.tar.gz
Resolved version spicyparrot-kafka-kraft-action-925b4bd
Run ./scripts/start.sh --version 3.7.0
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
Error: Process completed with exit code 126.
```

**Comment by asheswook** [comment] 2024-08-08 05:29
This is because your workflow uses `postgres:16-alpine` **based on alpine image**. The alpine linux image not includes bash. I requested PR #18.

Because the repository maintainer does not check this problem immediately, it cannot fixed right now.
If you want to fix this problem now, maybe it can helps:

* use other postgres image, not an alpine one.
* for example `postgres:16-bullseye`

**Comment by ThisIsMissEm** [comment] 2024-08-08 06:00
We're running this action on ubuntu-latest, the fact that we've a container running that happens to use alpine shouldn't be the source of this issue?

**Comment by asheswook** [comment] 2024-08-08 06:15
Could you let me know what actions configuration file did you use? I'm not sure how do you use this.

**Comment by jdickson1992** [comment] 2024-08-08 18:53
Apologies about the delayed response and thanks for the write up.

Can you provide your _full_ workflow (redacting any sensitive information) so I can look into this further / reproduce?

**Comment by ThisIsMissEm** [comment] 2024-08-08 19:41
I no longer have it, since I abandoned running kafka for testing purposes. All I have is the information given above.

**Comment by asheswook** [comment] 2024-08-09 00:55
As your previous comment, postgres alpine should not be related to this issue as it is running inside container. So I don't know what is the problem, I'm not sure this PR #18 is helpful.

**Comment by jdickson1992** [comment] 2024-08-14 21:01
Closing as unable to reproduce. Willing to reopen if an example workflow is provided.

**Closed as completed by jdickson1992** 2024-08-14 21:01 UTC
